### ISSUE TITLE
Continued Development

### ISSUE THREAD

**Issue by steevo590** [logstash-plugins/logstash-filter-memcached#1]
Hey, was wondering if this plugin is continuing to be developed/supported, I have a couple of use cases that it has proven extremely valuable and was hoping that it is continued.

**Comment by jsvd** [comment]
Can you talk a bit more about these use cases and which features would be necessary to support them?

**Comment by steevo590** [comment]
the main one is on some log enrichment, I have a session ID and user ID, session is in all logs but user ID is not so I am using memcached as a dynamic enrichment source, basically if i have userID and SessionID, i write it to the cache with session being the key and user the value, then if i get a record without userID i pull it from the cache with the session, this creates a dynamic self enriching log stream

**Comment by jsvd** [comment]
@steevo590 from what I understood this can be achieved now with this memcache filter by using conditionals and two instances of the filter:

1. if event does not have have userID, use `memcached { get { .. => .. } }` to retrieve from cache
2. if event has userID, use `memcached { set {  .. => .. } }` to place it there

**Comment by steevo590** [comment]
Yeah, that is how I am doing it, my original question was more around continued development and it going beyond a experimental plugin

**Comment by jsvd** [comment]
the current plan is indeed to move it to the default distribution in a future minor version but there isn't any roadmap for this plugin other than addressing any bugs, evaluating enhancement requests and reviewing community contributed PRs.

**Comment by jsvd** [comment]
closing as question was answered, if you see any enhancements worth having or find bugs please open a separate issue.
